In [1]:
import numpy as np

In [2]:
a = np.array([5,6,7],dtype='int64')
print(a)

[5 6 7]


In [3]:
b = np.array([[2.0, 5.0, 6.0],[8.0,2.0,9.0]])
print(b)

[[2. 5. 6.]
 [8. 2. 9.]]


In [4]:
#dimensions
a.ndim

1

In [5]:
b.ndim

2

In [6]:
#shape
a.shape

(3,)

In [7]:
b.shape

(2, 3)

In [8]:
#type
a.dtype

dtype('int64')

In [9]:
b.dtype

dtype('float64')

In [10]:
#size in bytes
a.itemsize

8

In [11]:
b.itemsize

8

In [12]:
a.nbytes #size of complete array

24

In [13]:
b.nbytes

48

In [14]:
a = np.array([[10,21,22,2,8,9,12],[12,1,2,4,9,6,5]])
print(a)

[[10 21 22  2  8  9 12]
 [12  1  2  4  9  6  5]]


In [15]:
# get specific elements
a[0,3]

2

In [16]:
a[1,4]

9

In [17]:
a[1,-4]

4

In [18]:
print(a[0])

[10 21 22  2  8  9 12]


In [19]:
print(a[0,:])

[10 21 22  2  8  9 12]


In [20]:
print(a[:,2]) # column 2 

[22  2]


In [21]:
#changing the elements
print(a)

[[10 21 22  2  8  9 12]
 [12  1  2  4  9  6  5]]


In [22]:
a[0,2] = 12

In [23]:
print(a)

[[10 21 12  2  8  9 12]
 [12  1  2  4  9  6  5]]


In [24]:
a[:,3] = 3 # [2, 4] will be replaced with 3 in both rows
print(a)

[[10 21 12  3  8  9 12]
 [12  1  2  3  9  6  5]]


In [25]:
a[:,3] = [1,2]
print(a)

[[10 21 12  1  8  9 12]
 [12  1  2  2  9  6  5]]


In [26]:
#3rd array
b = np.array([[[3,4],[6,5]],[[1,5],[9,8]]])
print(b)

[[[3 4]
  [6 5]]

 [[1 5]
  [9 8]]]


In [27]:
# all zero matrics
np.zeros(4)


array([0., 0., 0., 0.])

In [28]:
#numpy.zeros(shape, dtype=float, order='C')
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.zeros((4,5,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [31]:
np.ones(4)

array([1., 1., 1., 1.])

In [32]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [34]:
np.full((3,3),3,dtype='float32')

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]], dtype=float32)

In [35]:
a

array([[10, 21, 12,  1,  8,  9, 12],
       [12,  1,  2,  2,  9,  6,  5]])

In [36]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [37]:
#random decimals
np.random.rand(4,2)

array([[0.11791661, 0.67780958],
       [0.3436293 , 0.61881913],
       [0.40770228, 0.98146714],
       [0.43357695, 0.75127308]])

In [38]:
np.random.random_sample(a.shape)

array([[0.87862223, 0.16517362, 0.85637746, 0.23148   , 0.99890996,
        0.67656158, 0.64221212],
       [0.60159881, 0.35337807, 0.42340095, 0.56898954, 0.35630309,
        0.82768328, 0.68118536]])

In [39]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [40]:
arr = np.array([[11,12,5]])
a1 = np.repeat(arr, 3, axis=0)
print(a1)

[[11 12  5]
 [11 12  5]
 [11 12  5]]


In [41]:
a1 = np.repeat(arr, 3, axis=1)
print(a1)

[[11 11 11 12 12 12  5  5  5]]


### Mathematics

In [42]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [43]:
a + 5 # 5 is added to each element

array([6, 7, 8, 9])

In [44]:
a - 3

array([-2, -1,  0,  1])

In [45]:
a * 3 # [1,2,3,4], every element * 3

array([ 3,  6,  9, 12])

In [46]:
a/3

array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [47]:
a//3

array([0, 0, 1, 1], dtype=int32)

In [48]:
b = np.array([5,6,7,8])

In [49]:
a + b

array([ 6,  8, 10, 12])

In [50]:
a**2

array([ 1,  4,  9, 16])

In [51]:
a**3

array([ 1,  8, 27, 64], dtype=int32)

In [52]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [53]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [54]:
a = np.full((3,4),5)
b = np.full((4,5),4)
print(a)
print(b)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


In [55]:
np.matmul(a,b)

array([[80, 80, 80, 80, 80],
       [80, 80, 80, 80, 80],
       [80, 80, 80, 80, 80]])

In [56]:
c = np.identity(5)

In [57]:
np.linalg.det(c) #determinant of matrics

1.0

In [58]:
s = np.array([[1,2,3],[4,5,6]])
s

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
np.min(s, axis=0)

array([1, 2, 3])

In [60]:
np.min(s, axis=1)

array([1, 4])

In [61]:
np.max(s)

6

In [62]:
np.sum(s)

21

In [63]:
np.sum(s, axis=1)

array([ 6, 15])

In [64]:
b1 = np.array([[2,4,6,8],[1,3,5,7]])
b1

array([[2, 4, 6, 8],
       [1, 3, 5, 7]])

In [65]:
a1 = b1.reshape((4,2))
print(a1)

[[2 4]
 [6 8]
 [1 3]
 [5 7]]


In [66]:
#vertical stacking
v1 = np.array([2,4,6,8])
v2 = np.array([1,3,4,5])

In [67]:
np.vstack([v1,v2])

array([[2, 4, 6, 8],
       [1, 3, 4, 5]])

In [68]:
np.hstack([v1,v2])

array([2, 4, 6, 8, 1, 3, 4, 5])

In [69]:
Data = np.genfromtxt('array.txt', delimiter = ',')

In [70]:
print(Data)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


### Boolean Masking and Advanced Indexing

In [71]:
Data == 2

array([[False,  True, False, False, False],
       [False, False, False, False, False]])

In [72]:
a = np.array([10,20,30,40,50,60,70,80,90,100])
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [73]:
a[[2,5,8]] #2nd, 5th, 8th elements

array([30, 60, 90])

In [74]:
np.any(a>50, axis=0) # one or more elements from array are greater than 50

True